### PR TITLE
Specify length of array when controllers are connected/disconnected.

### LINKED ISSUE #82: Length of getGamepads() array
The spec describes the length of the array returned by getGamepads() in terms of the indices of Gamepad objects in the returned array. However, it doesn't describe the length when there are no objects in the array.

Should it specify an empty array when there are no connected gamepads?

Also, should the array shrink-to-fit when gamepads are disconnected?

### PR DESCRIPTION
**Pull request by knyg**
Closes #82 

The following tasks have been completed:

 * [ ] Modified Web platform tests (link to pull request)

Implementation commitment:

 * [ ] WebKit (https://bugs.webkit.org/show_bug.cgi?id=)
 * [ ] Chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=)
 * [ ] Gecko (https://bugzilla.mozilla.org/show_bug.cgi?id=)

***
<a href="https://pr-preview.s3.amazonaws.com/knyg/gamepad/pull/104.html" title="Last updated on Sep 19, 2019, 5:14 AM UTC (050392f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/gamepad/104/2c694ec...knyg:050392f.html" title="Last updated on Sep 19, 2019, 5:14 AM UTC (050392f)">Diff</a>

### CODE REVIEW

**Comment by sagoston** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by sagoston** [comment]
Marked as  substantive for IPR from ash-nazg.

**Comment by sagoston** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by sagoston** [comment]
Marked as  substantive for IPR from ash-nazg.

**Comment by ylafon** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by marcoscaceres** [comment]
@nondebug, I think this can be closed by looking at the merge conflict. The spec seems to already cover this?

**Comment by nondebug** [comment]
Yes let's close this and resolve the issue, the problematic language about the array size has already been removed.

**Pull request closed without merging**
