### PR TITLE
Add Brandon Jones as spec editor

### LINKED ISSUE #44: Add Brandon as editor
@Toji is now co-editor for this spec, so should be listed amongst the editors.

### PR DESCRIPTION
**Pull request by toji**
Might as well have my name on the doc if I'm actually going to be editing this thing. :)

Fixes #44

### CODE REVIEW

**Comment by sgraham** [comment]
I just  got a notification from GitHub Pages that the Jekyll build failed, I guess after this change. Unfortunately, it's dumb and doesn't give an error message other than "Page build failed". I don't immediately see any (new) problem, but maybe the trailing comma was breaking a strict js parser?

Otherwise, it could be anywhere in the body too, so might be completely unrelated to this change.

**Comment by toji** [comment]
Oh joy. Trailing comma was present on Ted's entry before, so I don't think that's it. More likely is a pre-existing change that didn't get processed until just now. (OR gh-pages just has a grudge against me specifically.)

**Comment by sgraham** [comment]
Yeah, I noticed Ted's entry already has it, but maybe that's what's broken anyway? I'm not sure. I don't have Jekyll set up at the moment to try to get an actual useful message, sorry.

**Comment by LJWatson** [comment]
@siusin is this something you can help with?

**Pull request merged**
